### ISSUE TITLE
文档中有错链导致无法正常重定向到「纸娃娃」

### ISSUE THREAD

**Issue by pacexy** [Kritsu/ExtractorSharp#9]
## 问题描述
[纸娃娃 | ExtractorSharp](https://es.kritsu.net/guide/plugin/avatar.html#%E7%BA%B8%E5%A8%83%E5%A8%83) 中的 url 末尾少了一个 slash(/) 导致不能正常重定向
[时装制作 | ExtractorSharp](https://es.kritsu.net/example/dress.html#%E5%9B%BE%E6%96%87) 这里的 url 是对的

## 参考
[谈一谈URL中位于最末尾的那条斜杠](https://zhuanlan.zhihu.com/p/54561817)

**Comment by chizukicn** [comment]
已解决
